### ISSUE TITLE
Hi, is there documentation on how to use this?

### ISSUE THREAD

**Issue by 1951FDG** [SapuSeven/NotiCap#1]
Hi, 

Is there documentation on how to use this? If I understand correctly, I could make an app and have it send a notification containing the ssh command/s to pass along to NotiCap who will send the command via ssh? Can NotiCap be used as an ssh helper for apps who don't wan't to implement the SSH functionality themselves? 

Best Regards,

**Comment by SapuSeven** [comment]
Hello,

In NotiCap you can define filters, and when a notification matching a filter is received, an SSH connection is being established and some commands will be sent. These commands and the details of the SSH connection have to be specified in the filter.

There's no option (yet) to have NotiCap send commands from another app.

**Comment by 1951FDG** [comment]
Hi,

Thanks for the info, when I get around to compiling Noticap and testing it, I'll get back to this!

Update, I've decided to use JuiceSSH!
